# mongodb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: todo-app
type: Opaque
data:
  mongodb-uri: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvdG9kb19hcHA= # base64 encoded mongodb://mongodb:27017/todo_app
  jwt-secret: eW91cl9zZWNyZXRfa2V5 # base64 encoded your_secret_key